### ISSUE TITLE
[BUG] v2.0.0. ALPHA:  Servicegroup ERROR when creating 2 servers as binding members

### ISSUE THREAD

**Issue by krausi24** [netscaler/ansible-collection-netscaleradc#270]
**Describe the bug**
Servicegroup ERROR when creating 2 servers as binding members:

TASK [netscaler_LSG : Setup servicegroup with members] ********************************************************************************************************************************************************************************************************************************************************
changed: [dkr_adc8 -> localhost] => (item={'LS_name': 'LS_S-CTXSF-2', 'LS_ip': '10.205.81.24', 'LS_port': '80'})
<SNIP>
{'errorcode': 1092, 'message': 'Arguments cannot both be specified [serverName, IP]', 'severity': 'ERROR'}"}

**To Reproduce**
TASK:
---
- name: Setup servicegroup with members
  tags: servicegroup
  delegate_to: localhost
  netscaler.adc.servicegroup:
    nsip: "{{ ansible_host }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"
    validate_certs: "{{ validate_certs }}"
    state: "{{ state }}"

    servicegroupname: "{{ LSG_name }}"
    servicetype: "{{ LSG_service }}"
    servicegroup_servicegroupmember_binding:
      mode: desired
      binding_members:
        - ip: "{{ item.LS_ip }}"
          port: "{{ item.LS_port }}"
          servicegroupname: "{{ LSG_name }}"
  loop: "{{ netscaler_LS }}"

Variable:
netscaler_LS:
  - LS_name: "LS_S-CTXSF-2"
    LS_ip: "10.205.81.24"
    LS_port: "80"
  - LS_name: "LS_S-CTXSF-1"
    LS_ip: "10.205.81.23"
    LS_port: "80"

**Expected behaviour**
The other server is added too:
(changed: [dkr_adc8 -> localhost] => (item={'LS_name': 'LS_S-CTXSF-1', 'LS_ip': '10.205.81.23', 'LS_port': '80'}))

.

**Environment (please complete the following information):**
ansible [core 2.14.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dkr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/dkr/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

Python 3.10.6

**Additional context**
It seems the second API call takes the "servicegroupname" falsely as "servername"

**Comment by sumanth-lingappa** [comment]
@krausi24 I tried with the following playbook, it worked as expected. Please let me know if I'm missing something.

>  Request you to format the YAML code in the issues :-)

```yaml
- name: Issue 270
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Setup servicegroup with members
      delegate_to: localhost
      netscaler.adc.servicegroup:
        servicegroupname: demo-sg
        servicetype: HTTP
        servicegroup_servicegroupmember_binding:
          mode: desired
          binding_members:
            - ip: 1.1.1.1
              port: 80
              servicegroupname: demo-sg
            - ip: 2.2.2.2
              port: 80
              servicegroupname: demo-sg

```

Below is the resultant `servicegroup` created in `netscaler`

```bash
> show servicegroup demo-sg
        demo-sg - HTTP
        State: ENABLED  Effective State: DOWN   Monitor Threshold : 0
        Max Conn: 0     Max Req: 0      Max Bandwidth: 0 kbits
        Use Source IP: NO
        Client Keepalive(CKA): NO
        Monitoring Owner: 0
        TCP Buffering(TCPB): NO
        HTTP Compression(CMP): NO
        Idle timeout: Client: 180 sec   Server: 360 sec
        Client IP: DISABLED
        Cacheable: NO
        SC: ???
        SP: OFF
        Down state flush: ENABLED
        Monitor Connection Close : NONE
        Appflow logging: ENABLED
        ContentInspection profile name: ???
        Process Local: DISABLED
        Traffic Domain: 0


        1)         2.2.2.2:80   State: DOWN     Server Name: 2.2.2.2    Server ID: None Weight: 1       Order: Default
                Last state change was at Mon Sep 25 08:56:55 2023
                Time since last state change: 0 days, 00:03:48.300

                Monitor Name: tcp-default       State: DOWN     Passive: 0
                Probes: 14      Failed [Total: 14 Current: 14]
                Last response: Failure - No MIP/SNIP available to send the monitor probe.
                Response Time: 0 millisec

        2)         1.1.1.1:80   State: DOWN     Server Name: 1.1.1.1    Server ID: None Weight: 1       Order: Default
                Last state change was at Mon Sep 25 08:56:54 2023
                Time since last state change: 0 days, 00:03:49.230

                Monitor Name: tcp-default       State: DOWN     Passive: 0
                Probes: 14      Failed [Total: 14 Current: 14]
                Last response: Failure - No MIP/SNIP available to send the monitor probe.
                Response Time: 0 millisec
 Done
>
```
