### ISSUE TITLE
[BUG] v2.0.0. ALPHA: "Cannot change value for the following non-updateable attributes ['ip']" when using 127.0.0.1 als IP in Service

### ISSUE THREAD

**Issue by krausi24** [netscaler/ansible-collection-netscaleradc#271]
**Describe the bug**
Creating a dummy "Always Up" service with IP 127.0.0.1. The IP will then be shown as the NSIP in GUI. When Ansible module checks the desired state it recognizes a different and tries to add the service which fails. 

**To Reproduce**
Steps to reproduce the behaviour:

- name: Setup service 
  tags: service
  delegate_to: localhost
  netscaler.adc.service:
    nsip: "{{ ansible_host }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"
    validate_certs: "{{ validate_certs }}"
    state: "{{ state }}"
    
    name: "{{ LSC_name }}" 
    ip: "{{ LSC_ip }}"
    servicetype: "{{ LSC_servicetype }}"
    port: "{{LSC_port}}"
    healthmonitor: "{{LSC_healthmonitor}}"

Variables:
LSC_name: "LSC_dummy"
LSC_ip: "127.0.0.1"
LSC_servicetype: "HTTP"
LSC_port: "9999"
LSC_healthmonitor: "False"

**Expected behaviour**
Module should not try to update the service when 127.0.0.1 is provided as service IP. 

**Screenshots**
![image](https://github.com/citrix/citrix-adc-ansible-modules/assets/128399931/e4564de8-509f-4d62-9353-4b6909a67e24)

**Environment (please complete the following information):**
ansible [core 2.14.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dkr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/dkr/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

**Comment by sumanth-lingappa** [comment]
NITRO's `service` resource has a strange behaviour of accepting `ip` attribute in it's POST request and `ipaddress` attribute in it's PUT request.

This special case has been handled in `netscaler.adc.service` module.

Recommendation is to use `ipaddress` instead of `ip` in your `netscaler.adc.service` task.

> I will keep this issue open to accept `ip` in `netscaler.adc.service` module

So, your playbook should be:

```yaml
- name: Setup service
  tags: service
  delegate_to: localhost
  netscaler.adc.service:
  nsip: "{{ ansible_host }}"
  nitro_user: "{{ nitro_user }}"
  nitro_pass: "{{ nitro_pass }}"
  validate_certs: "{{ validate_certs }}"
  state: "{{ state }}"

  name: "{{ LSC_name }}"
  ipaddress: "{{ LSC_ip }}"  # <<<<<<<<<< Use `ipaddress` instead of `ip` attribute
  servicetype: "{{ LSC_servicetype }}"
  port: "{{LSC_port}}"
  healthmonitor: "{{LSC_healthmonitor}}"
```
