### ISSUE TITLE
[BUG] v2.0.0. ALPHA:  When using port number 0 the module lbvserver wir fail with port missing error

### ISSUE THREAD

**Issue by krausi24** [netscaler/ansible-collection-netscaleradc#272]
**Describe the bug**
Goal is to add a non-addressable lbvserver.
Error is:
status_code: 400; Reason:{'errorcode': 1095, 'message': 'Required argument missing [port]'

**To Reproduce**
- name: Create a load balancing vserver bound to service
  tags: lbvserver_w_service
  delegate_to: localhost
  netscaler.adc.lbvserver:
    nsip: "{{ ansible_host }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"
    validate_certs: "{{ validate_certs }}"
    state: "{{ state }}"

    name: "{{ LVS_name_1 }}"
    servicetype: "{{ LVS_service_1 }}"
    ipv46: "{{ LVS_ip_1 }}"
    port: "{{ LVS_port_1 }}"
    lbvserver_service_binding:
      binding_members:
        - name: "{{ LVS_name_1 }}"
          servicename: "{{ LVS_svc_name_1}}"

variables:
LVS_name_1: "LVS_NGVS_RootURI"
LVS_service_1: "HTTP"
LVS_port_1: 0

**Expected behaviour**
Non-addressable vserver can be added with port 0.

**Screenshots**
![image](https://github.com/citrix/citrix-adc-ansible-modules/assets/128399931/10b469b8-edad-4836-b6e2-63339a7eef8c)

**Environment (please complete the following information):**
ansible [core 2.14.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dkr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/dkr/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

**Additional context**
I tried it with 0 and "0" and both leads to an missing port argument in the API call.

**Comment by sumanth-lingappa** [comment]
This is fixed in the latest ansible collection. Please re-install the collection.

Below is the playbook used to validate this issue:

```yaml
- name: Issue 272
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create a load balancing vserver bound to service
      delegate_to: localhost
      netscaler.adc.lbvserver:
        name: LVS_NGVS_RootURI
        servicetype: HTTP
        ipv46: 0.0.0.0
        port: 0
```
