### ISSUE TITLE
[BUG] v2.0.0. ALPHA:  authenticationvserver_authenticationpolicy_binding ERROR for sso value when set to "True"

### ISSUE THREAD

**Issue by krausi24** [netscaler/ansible-collection-netscaleradc#273]
**Describe the bug**
Using authenticationvserver_authenticationpolicy_binding and set the sso value to "True" results in ERROR:
 400; Reason:{'errorcode': 1097, 'message': 'Invalid argument value [true]'
Using value "ON" instead of "True" the ERROR is:
"msg": "value of sso must be one of: True, False, got: ON"

**To Reproduce**
- name: Create VPN Session Profile RN
  tags: vpnsessionaction_rn
  delegate_to: localhost
  netscaler.adc.vpnsessionaction:
    nsip: "{{ ansible_host }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"
    validate_certs: "{{ validate_certs }}"
    state: "present" 

    name: "{{ NGSPR_RN_name }}"
    homepage: "{{ NGSPR_homepage_RN }}"
    advancedclientlessvpnmode: "{{ NGSPR_advancedclientlessvpnmode_RN }}"
    wihome: "{{ NGSPR_wihome_RN }}"
    sesstimeout: "{{ NGSPR_sesstimeout_RN }}"
    clientlessvpnmode: "{{ NGSPR_clientlessvpnmode_RN }}"
    clientlessmodeurlencoding: "{{ NGSPR_clientlessmodeurlencoding_RN }}"
    sso: "{{ NGSPR_sso_RN }}"
    ssocredential: "{{ NGSPR_ssocredential_RN }}"
    icaproxy: "{{ NGSPR_icaproxy_RN }}"
    storefronturl: "{{ NGSPR_storefronturl_RN }}"

Variables:
NGSPR_sso_RN: True

**Expected behaviour**
Value "True" should result in the correct API call without error.

**Screenshots**
![image](https://github.com/citrix/citrix-adc-ansible-modules/assets/128399931/8f3af566-c2c6-41a7-a115-15c930a46f58)

**Environment (please complete the following information):**
ansible [core 2.14.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dkr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/dkr/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

**Comment by sumanth-lingappa** [comment]
Thank you for raising this ticket @krausi24.

This is fixed in the latest release. Please re-install the `netscaler.adc` collection

> Since ON and OFF are termed as booleans by YAML parser, it is recommended to enclose these in quotes as stated below

Please re-open this issue if this issue still persists at your end.

You can find the documentation for this module below:
- https://netscaler.github.io/ansible-collection-netscaleradc/collections/netscaler/adc/vpnsessionaction_module.html#ansible-collections-netscaler-adc-vpnsessionaction-module

Also, you can find a sample working playbook task below

```yaml
- name: Create VPN Session Profile RN
  hosts: localhost
  gather_facts: false
  tasks:
    - netscaler.adc.vpnsessionaction:
        name: demo-session
        homepage: https://example.com
        advancedclientlessvpnmode: DISABLED
        wihome: https://example.com
        sesstimeout: 600
        clientlessvpnmode: 'ON' # <<<< Enclose with quotes
        clientlessmodeurlencoding: TRANSPARENT
        sso: 'ON' # <<<< Enclose with quotes
        ssocredential: PRIMARY
        icaproxy: 'ON' # <<<< Enclose with quotes
        storefronturl: https://example.com
```
