### ISSUE TITLE
[FEATURE REQUEST] _info modules

### ISSUE THREAD

**Issue by fa-elepape** [netscaler/ansible-collection-netscaleradc#296]
**Is your feature request related to a problem? Please describe.**
While the new collection lets Ansible manage pretty much all aspects of Netscaler, it's not currently possible to retrieve information from them.

In my current case, I'm attempting to renew certificates which are relatively close to expiry but retrieving that information is not readily available from `_info` modules (see [vmware.vmware_rest](https://docs.ansible.com/ansible/latest/collections/vmware/vmware_rest/index.html) for an example) which means I have to fall back to using the `ansible.builtin.uri` module to perform those requests.

I'm raising this feature request to make this more "Ansibly" but it's clearly not a blocker.

**Describe the solution you'd like**
Add corresponding `_info` modules to the existing modules.

**Describe alternatives you've considered**
Again, this is not (for me) a blocking issue since I can perform the requests manually for now, it's just more cumbersome.

**Comment by sumanth-lingappa** [comment]
@fa-elepape, thank you for the enhancement request. This is a very apt ask.
We will definitely keep this in our planning.

Can you please share your workaround using `ansible.builtin.uri` which you mentioned?

**Comment by fa-elepape** [comment]
Sure! It's really just a dump of the [`/sslcertkey` endpoint](https://developer-docs.netscaler.com/en-us/adc-nitro-api/current-release/configuration/ssl/sslcertkey) of the NITRO API which can then be manipulated using Ansible. It's quite close to what was documented in the [_citrix.adx_ branch](../blob/citrix.adc/docs/generic_modules/nitro_api_calls.rst#playbook).

```yaml
ansible.builtin.uri:
  url: "{{ nitro_protocol }}://{{ nsip }}/nitro/v1/config/sslcertkey"
  method: GET
  status_code: 200
  return_content: yes
  headers:
    X-NITRO-USER: "{{ nitro_user }}"
    X-NITRO-PASS: "{{ nitro_pass }}"
  validate_certs: "{{ validate_certs }}"
vars:
  nitro_pass: "{{ netscaler_nitro_pass | default(lookup('ansible.builtin.env', 'NETSCALER_NITRO_PASS', omit)) }}"
  nitro_protocol: "{{ netscaler_nitro_protocol | default(lookup('ansible.builtin.env', 'NETSCALER_NITRO_PROTOCOL')) }}"
  nitro_user: "{{ netscaler_nitro_user | defaut(lookup('ansible.builtin.env', 'NETSCALER_NITRO_USER', omit)) }}"
  nsip: "{{ netscaler_nsip | default(lookup('ansible.builtin.env', 'NETSCALER_NSIP', omit)) }}
  validate_certs: "{{ netscaler_validate_certs | default(lookup('ansible.builtin.env', 'NETSCALER_VALIDATE_CERTS', omit)) }}
```
