### ISSUE TITLE
[FEATURE REQUEST]: Register modules within `action_groups`

### ISSUE THREAD

**Issue by fa-elepape** [netscaler/ansible-collection-netscaleradc#307]
### Summary

All (I think) modules within the collection use the same parameters when determining how and where to address the NetScaler instance:
- `api_path`
- `nitro_auth_token`
- `nitro_pass`
- `nitro_protocol`
- `nitro_user`
- `nsip`
- `save_config`
- `validate_certs`

Given the wide range of modules available, `module_defaults` is hardly usable, and specifying parameters everywhere is tiresome which makes environment variables the only viable solution (IMO). Registering the modules within an action group would make using `module_defaults` far easier.

Action groups aren't documented within the [Collection Galaxy metadata structure](https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html) documentation but within the [Module defaults](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_module_defaults.html#module-defaults-groups).

### Issue Type

Feature Idea

### Component Name

*

### Describe alternatives you've considered

The environment variable works just fine, this Feature Request is an enhancement, not a blocker.

### Additional Information

```yaml
- name: NetScaler playbook
  module_defaults:
    groups/netscaler.adc.config:
      api_path: /prefix
      nitro_auth_token: !vault |
        ...
      nitro_user: me
      nsip: netscaler.example.com
      save_config: true
      validate_certs: true

  tasks:
  - netscaler.adc.server:
      domain: example.com
      name: example.com
  - netscaler.adc.servicegroup:
      servicegroupname: example.com
      servicetype: SSL
  - netscaler.adc.sslprofile:
      name: example
      ocspstapling: 'ENABLED'
```
