### ISSUE TITLE
[Bug]: "ERROR: Primary key `serverip` is missing for the resource `ntpserver`"

### ISSUE THREAD

**Issue by gjonn** [netscaler/ansible-collection-netscaleradc#322]
### Summary

When trying to create a ntpserver using only the hostname I get the error:

ERROR: Primary key `serverip` is missing for the resource `ntpserver`

But then if you provide it:
'errorcode': 1092, 'message': 'Arguments cannot both be specified [serverName, serverIP]', 'severity': 'ERROR'

### Issue Type

Bug Report

### Component Name

netscaler.adc.ntpserver

### Python Version

```console (paste below)
$ python --version # or python3 --version
Python 3.10.12
```

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.5]
```

### Ansible Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### netscaler.adc Collection Version

```console (paste below)
$ ansible-galaxy collection list netscaler.adc
netscaler.adc 2.1.0
```

### Target NetScaler Version

```console (paste below)
> show ns version

```

### Equivalent NetScaler CLI Command

```console (paste below)

```

### Steps to Reproduce

```yaml (paste below)
- name: NTP Configuration
  delegate_to: localhost
  netscaler.adc.ntpserver:
    nsip: "{{ inventory_hostname }}"
    servername: 'pool.ntp.org'
    preferredntpserver: "YES"
    state: present

```

### Expected Results

Add an NTP server by dns hostname only

### Actual Results

```console (paste below)

```
