### ISSUE TITLE
[Bug]: lbmonitor (netscaler.adc 2.1.0)

### ISSUE THREAD

**Issue by pkodzis** [netscaler/ansible-collection-netscaleradc#324]
### Summary

ansible keeps modifing lbmonitor while there have been zero changes in playbook

### Issue Type

Bug Report

### Component Name

lbmonitor

### Python Version

```console (paste below)
$ python --version # or python3 --version

```
3.9

### Ansible Version

```console (paste below)
$ ansible --version

```
2.15.6

### Ansible Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### netscaler.adc Collection Version

```console (paste below)
$ ansible-galaxy collection list netscaler.adc

```
2.1.0

### Target NetScaler Version

```console (paste below)
> show ns version

```

### Equivalent NetScaler CLI Command

```console (paste below)

```

### Steps to Reproduce

```yaml (paste below)
            - interval: 60
              state: present
              type: HTTP
              deviation: 0
```

### Expected Results

created at the first playbook run. then all the next playbook runs zero change.

### Actual Results

```console (paste below)
 {
-    "deviation": "0",
-    "interval": 1,
+    "deviation": 0.0,
+    "interval": 60,
[...]
```

**Comment by sumanth-lingappa** [comment]
@pkodzis, can you please help me with 

1. the complete task
2. output of the ansible playbook with -vvv option

**Comment by pkodzis** [comment]
@sumanth-lingappa , this is example task that gives this behavior:

```
    - name: setup lbmonitor
      delegate_to: localhost
      netscaler.adc.lbmonitor:
        nsip: "{{ provider.nsip }}"
        nitro_auth_token: "{{ provider.nitro_auth_token | default(omit) }}"
        nitro_protocol: "{{ provider.nitro_protocol | default(omit) }}"
        validate_certs: "{{ provider.validate_certs | default(omit) }}"
        monitorname: test-monitor-1
        interval: 60
        state: present
        type: HTTP
        deviation: 0
```
[deploy_test-1.log](https://github.com/netscaler/ansible-collection-netscaleradc/files/13724930/deploy_test-1.log)
[deploy_test-2.log](https://github.com/netscaler/ansible-collection-netscaleradc/files/13724931/deploy_test-2.log)
[deploy_test-3.log](https://github.com/netscaler/ansible-collection-netscaleradc/files/13724932/deploy_test-3.log)

attachgin logs. log #1 creates the monitor. logs #2 and #3 are from re-deploy of the same task, so ansible should make no changes.
