### ISSUE TITLE
[FEATURE REQUEST]: save configuration module

### ISSUE THREAD

**Issue by pkodzis** [netscaler/ansible-collection-netscaleradc#326]
### Summary

Please provide module that will let saving configuration

### Issue Type

Feature Idea

### Component Name

general

### Additional Information

```yaml (paste below)

```

**Comment by sumanth-lingappa** [comment]
Please check the new release `2.2.0` -- `save_config` module and update the issue

sample playbook:

https://github.com/netscaler/ansible-collection-netscaleradc/blob/main/examples/save_config.yaml

**Comment by pkodzis** [comment]
wow, that was super-quick! :)
I didnt test option "all", while we don't use it. We always save per-partition:

```
    - name: save_config
      delegate_to: localhost
      netscaler.adc.save_config:
        nsip: "{{ provider.nsip }}"
        nitro_auth_token: "{{ provider.nitro_auth_token | default(omit) }}"
        nitro_protocol: "{{ provider.nitro_protocol | default(omit) }}"
        validate_certs: "{{ provider.validate_certs | default(omit) }}"
```

The test passed - Ansible returned success:
```
DEBUG: save_config nsconfig SUCCESS
```

On device I can see it did modify only expected config file:
```
# find /nsconfig/* -name ns.conf -exec ls -l {} \;
-rw-------  1 root  wheel  36235 Dec 14 15:38 /nsconfig/ns.conf
-rw-------  1 root  wheel  132863 Dec 15 15:27 /nsconfig/partitions/PROD/ns.conf
-rw-------  1 root  wheel  34943 Dec 21 11:11 /nsconfig/partitions/DEV/ns.conf
```


Attaching the log:
[save_config_test-1.log](https://github.com/netscaler/ansible-collection-netscaleradc/files/13740678/save_config_test-1.log)
These are msgs there that I guess should not appear, so maybe there is something else in backgroud that needs to be tweaked:
```
        "TRACE: EXIT: send() returned (400, {'errorcode': 1232, 'message': 'Invalid object name [save_config]', 'severity': 'ERROR'})",
        "TRACE: EXIT: get() returned (400, {'errorcode': 1232, 'message': 'Invalid object name [save_config]', 'severity': 'ERROR'})",
```
