### ISSUE TITLE
[Bug]: Cipher Group recreating even if exists

### ISSUE THREAD

**Issue by gjonn** [netscaler/ansible-collection-netscaleradc#350]
### Summary

When I create a cipher group, the initial add works. If i run the playbook again, it doesn't find the group it just created and tries to create it again, which fails.

### Issue Type

Bug Report

### Component Name

netscaler.adc.sslcipher

### Python Version

```console (paste below)
$ python --version # or python3 --version
Python 3.10.12
```

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.5]
```

### Ansible Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### netscaler.adc Collection Version

```console (paste below)
$ ansible-galaxy collection list netscaler.adc
Collection    Version
------------- -------
netscaler.adc 2.4.0
```

### Target NetScaler Version

```console (paste below)
> show ns version
14.1
```

### Equivalent NetScaler CLI Command

```console (paste below)

```

### Steps to Reproduce

```yaml (paste below)
- name: Cipher Group
  delegate_to: localhost
  netscaler.adc.sslcipher:
    nsip: "{{ inventory_hostname }}"
    ciphergroupname: ciphertest
    state: present
```

Run twice

### Expected Results

The first one succeeds and creates the cipher group. The second run errors out because the group already exists, instead of reporting "ok".

### Actual Results

```console (paste below)

```
