### ISSUE TITLE
[Bug]: hasync module missing state values

### ISSUE THREAD

**Issue by rich549** [netscaler/ansible-collection-netscaleradc#360]
### Summary

The module doesn't allow for any values to be set, it returns an error of:

fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of state must be one of: , got: present"}

The options in the documentation allow for present as default but the Python code doesn't allow this.

### Issue Type

Bug Report

### Component Name

netscaler.adc.hasync

### Python Version

```console (paste below)
$ python --version # or python3 --version
Python 3.10.12
```

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.8]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/admin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/admin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Ansible Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### netscaler.adc Collection Version

```console (paste below)
$ ansible-galaxy collection list netscaler.adc
netscaler.adc 2.4.0
```

### Target NetScaler Version

```console (paste below)
> show ns version
netscaler.adc 2.4.0
```

### Equivalent NetScaler CLI Command

```console (paste below)

```

### Steps to Reproduce

```yaml (paste below)
  - name: Sync HA Config
    netscaler.adc.hasync:
      nsip: "{{ netscaler_ip }}"
      nitro_auth_token: "{{ login_result.sessionid }}"
      state: present
      save_config: yes
      save: 'YES'
      force: true
```

### Expected Results

I expected the module to use the default value of 'present', however it doesn't accept this. #

### Actual Results

```console (paste below)
fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of state must be one of: , got: present"}
```
