### ISSUE TITLE
[Bug]: Systemuser "unset" not working

### ISSUE THREAD

**Issue by krausi24** [netscaler/ansible-collection-netscaleradc#400]
### Summary

Setting the state to "unset" results in error:
fatal: [dkr_adc4 -> localhost]: FAILED! => {"changed": false, "msg": "value of state must be one of: absent, present, got: unset"}

According documentation it should be possible:
![image](https://github.com/netscaler/ansible-collection-netscaleradc/assets/128399931/a80bcec6-43ab-4f4f-ac35-3ba2c8b536a3)

### Issue Type

Bug Report

### Component Name

netscaler.adc.systemuser

### Python Version

```console (paste below)
Python 3.10.6


```

### Ansible Version

```console (paste below)
ansible [core 2.14.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dkr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/dkr/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Ansible Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### netscaler.adc Collection Version

```console (paste below)
Collection    Version
------------- -------
netscaler.adc 2.0.1  
```

### Target NetScaler Version

```console (paste below)
14.1 17.38

```

### Equivalent NetScaler CLI Command

```console (paste below)

```

### Steps to Reproduce

```yaml
- name:
  tags: SYSTEMUSER_edit 
  delegate_to: localhost
  netscaler.adc.systemuser:
    nsip: "{{ ansible_host }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"
    validate_certs: "{{ validate_certs }}"
    state: "unset"
    
    username: "{{ item['SYSTEMUSER_username'] }}"
    externalauth: "{{ item['SYSTEMUSER_externalauth'] }}"

```

### Expected Results

Unset is working

### Actual Results

```console (paste below)

```
