### ISSUE TITLE
[Bug]: Unable to update existing file

### ISSUE THREAD

**Issue by Callisto88** [netscaler/ansible-collection-netscaleradc#496]
### Summary

Hi,

I am trying to manage files in the Netscaler like TLS certificates and licenses files. 
Unfortunately i cannot figure out how to manage file changes properly.

Thank you for your help.
Regards

### Issue Type

Bug Report

### Component Name

netscaler.adc.systemfile

### Python Version

```console (paste below)
$ python --version # or python3 --version

Python 3.10.16
```

### Ansible Version

```console (paste below)
$ ansible --version

ansible [core 2.17.5]
  config file = /home/user/git/project/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/git/project/venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/git/project/venv/bin/ansible
  python version = 3.10.16 (main, Dec  4 2024, 08:53:38) [GCC 13.2.0] (/home/user/git/project/venv/bin/python3.10)
  jinja version = 3.1.3
  libyaml = True
```

### Ansible Configuration

```console (paste below)
$ ansible-config dump --only-changed

CALLBACKS_ENABLED(/home/user/git/project/ansible.cfg) = ['profile_tasks']
CONFIG_FILE() = /home/user/git/project/ansible.cfg
DEFAULT_HASH_BEHAVIOUR(/home/user/git/project/ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/user/git/project/ansible.cfg) = ['/home/user/git/project/inventory/01-hosts.yml', '/home/user/git/project/inventory/02>DEFAULT_ROLES_PATH(/home/user/git/project/ansible.cfg) = ['/home/user/git/project/roles', '/home/user/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansi>DEFAULT_TIMEOUT(/home/user/git/project/ansible.cfg) = 120
DEPRECATION_WARNINGS(/home/user/git/project/ansible.cfg) = False
HOST_KEY_CHECKING(/home/user/git/project/ansible.cfg) = False
INVENTORY_ENABLED(/home/user/git/project/ansible.cfg) = ['community.vmware.vmware_vm_inventory', 'yaml']
PAGER(env: PAGER) = less
PERSISTENT_COMMAND_TIMEOUT(/home/user/git/project/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/home/user/git/project/ansible.cfg) = 60
```

### netscaler.adc Collection Version

```console (paste below)
$ ansible-galaxy collection list netscaler.adc

Collection    Version
------------- -------
netscaler.adc 2.8.0
```

### Target NetScaler Version

```console (paste below)
> show ns version

        NetScaler NS14.1: Build 34.42.nc, Date: Oct 22 2024, 05:01:41   (64-bit)
```

### Equivalent NetScaler CLI Command

```console (paste below)

```

### Steps to Reproduce

Considering this task

```
- name: Upload file to NetScaler
  delegate_to: localhost
  netscaler.adc.systemfile:
      filename: "{{ item.split('/') | last }}"
      filecontent: "{{ lookup('file', item) | b64encode }}"
      filelocation: "/nsconfig/ssl/"
      fileencoding: "BASE64"
  with_fileglob:
    - files/netscaler/certs/all/*.cer
  tags:
    - systemfile
```

First run (initial upload) : works fine. The file get uploaded.

```
TASK [Upload file to NetScaler] ************************************************************************************************************************************************************Wednesday 19 March 2025  12:09:36 +0100 (0:00:00.070)       0:00:00.070 *******                                                                                                             --- before                                                                                                                                                                                  +++ after                                                                                                                                                                                   @@ -1 +1,6 @@                                                                                                                                                                               -{}
+{
+    "filecontent": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdMekNDQkJlZ0F3SUJBZ0lURmdBQUFBYjQwQTlsOGNmOEl3QUFBQUFBQmpBTkJna3Foa2lHOXcwQkFRc0YKQURBV01SUXdFZ1lEVlFRREV3dFNiMjkwUTBFdFQwTldVekFlRncweU16QTFNa

[...]

EJNbmw4UXgvNVI5QldrK3RUQVZCZ05WSFNBRURqQU1NQW9HQ0NvREJJc3ZRMWtGTUJrR0NTc0dBUVFCCmdqY1VBZ1FNSGdvQVV3QjFBR0lBUXdCQk1Bc0dBMVVkRHdRRUF3SUJoakFQQmdOVkhSTUJBZjhFQlRBREFRSC8KTUI4R0ExVWRJd1FZTUJhQUZCYXQzWGNFdFZZQTNEVDdXSHJqdEZscWpLYkRNRU1HQTFVZEh3UThNRG93T0tBMgpvRFNHTW1oMGRIQTZMeTl3YTJrdWIyTjJjeTF6WVdVdWJHOWpZV3d2WTJWeWRHUmhkR0V2VW05dmRFTkJMVTlECmdqY1VBZ1FNSGdvQVV3QjFBR0lBUXdCQk1Bc0dBMVVkRHdRR,                                     
+    "fileencoding": "BASE64",                                                                                                                                                              +    "filelocation": "/nsconfig/ssl/",                                                                                                                                                      +    "filename": "dummy.cer"                                                                                                                                                                +}

changed: [netscaler -> localhost] => (item=/home/user/git/project/playbooks/files/netscaler/certs/all/dummy.cer)
```

File on the Netscaler FS

```
# ls -lah dummy.cer
-rw-r--r--  1 root  wheel   6.0K Mar 19 12:09 dummy.cer
```

Second run (no change) : works fine

```
TASK [Upload file to NetScaler] ************************************************************************************************************************************************************Wednesday 19 March 2025  12:11:24 +0100 (0:00:00.078)       0:00:00.078 *******
ok: [`netscaler -> localhost] => (item=/home/user/git/project/playbooks/files/netscaler/certs/all/dummy.cer)
```

Now let's change the file content and re-run the task

```
TASK [Upload file to NetScaler] ************************************************************************************************************************************************************Wednesday 19 March 2025  12:14:26 +0100 (0:00:00.056)       0:00:00.056 *******
ok: [netscaler -> localhost] => (item=/home/user/git/project/playbooks/files/netscaler/certs/all/dummy.cer)
[WARNING]: Resource systemfile/dummy.cer not updated because user is trying to update following non-updatable keys: ['filecontent']
```

Alright, according to the warning the `filecontent` is non-updatable -> `[WARNING]: Resource systemfile/dummy.cer not updated because user is trying to update following non-updatable keys: ['filecontent']` 

So my question is, how am i supposed to changes if i cannot update the file ?

### Expected Results

I expect the modified file to be uploaded

### Actual Results

No change reported

```console (paste below)
[WARNING]: Resource systemfile/dummy.cer not updated because user is trying to update following non-updatable keys: ['filecontent']
```

### Additional Notes

I tried a few approach to circumvent this limitation including some complex file handling like:

```
- name: Retrieve license file content
  ansible.builtin.uri:
    url: https://{{ ansible_host }}/nitro/v1/config/systemfile?args=filename:{{ item.split('/') | last }},filelocation:{{ '%2Fnsconfig%2Flicense%2F' }}
    method: GET
    return_content: true
    force_basic_auth: true
    validate_certs: false
    user: nsroot
    password: "{{ vault_netscaler_nsroot_pass }}"
    headers:
      Content-Type: "application/json"
    status_code:
      - 200
      - 599 # File does not exist.
  register: current_file
  check_mode: false
  with_fileglob:
    - "files/netscaler/licenses/{{ env }}/*"

- name: Debug current_file
  ansible.builtin.debug:
      msg: "{{ current_file.results | default([]) | json_query(query_filecontent) | first | ansible.builtin.md5 }}"
  with_fileglob:
      - "files/netscaler/licenses/{{ env }}/*"
  vars:
      query_filecontent: "[?item=='{{ item }}'].json.systemfile[0].filecontent"
      query_errcode: "[?item=='{{ item }}'].json.errorcode"
  when: >
      (current_file.results | default([]) | json_query(query_errcode) | first | default(None)) is not none and
      (current_file.results | default([]) | json_query(query_errcode) | first) != "3441"

- name: Debug lookup file
  ansible.builtin.debug:
      msg: "{{ (lookup('file', item) | b64encode) | ansible.builtin.md5 }}"
  with_fileglob:
      - "files/netscaler/licenses/{{ env }}/*"

- name: Delete the license file if content differs
  netscaler.adc.systemfile:
      filename: "{{ item.split('/') | last }}"
      filelocation: /nsconfig/license/
      state: absent
  when: >
      ((current_file.results | json_query(query_errcode) | first | default(None)) is not none and
      (current_file.results | json_query(query_errcode) | first | default(None)) != "3441") or
      ((current_file.results | json_query(query_filecontent) | first | default(None)) is not none and
      (current_file.results | json_query(query_filecontent) | first | default(None) | ansible.builtin.md5 !=
      (lookup('file', item) | b64encode | ansible.builtin.md5)))
  # when: current_file.results | json_query(query_filecontent) | first | ansible.builtin.md5 != (lookup('file', item) | b64encode) | ansible.builtin.md5
  with_fileglob:
      - "files/netscaler/licenses/{{ env }}/*"
  vars:
      query_filecontent: "[?item=='{{ item }}'].json.systemfile[0].filecontent"
      query_errcode: "[?item=='{{ item }}'].json.errorcode"

- name: Upload license file
  netscaler.adc.systemfile:
      filename: "{{ item.split('/') | last }}"
      filecontent: "{{ lookup('file', item) | b64encode }}"
      filelocation: /nsconfig/license/
  # when: current_file.results[item_index].json.systemfile[0].filecontent != (lookup('file', item) | b64encode) and not ansible_check_mode
  when: >
      ((current_file.results | json_query(query_filecontent) | first | default(None)) is not none and
      (current_file.results | json_query(query_filecontent) | first | default(None) | ansible.builtin.md5 !=
      (lookup('file', item) | b64encode | ansible.builtin.md5)))
  with_fileglob:
      - "files/netscaler/licenses/int/*"
  loop_control:
      index_var: item_index
  vars:
      query_filecontent: "[?item=='{{ item }}'].json.systemfile[0].filecontent"
      query_errcode: "[?item=='{{ item }}'].json.errorcode"
```

I have the feeling it's not the way.
