### ISSUE TITLE
[Bug]: netscaler.adc.install supports no state

### ISSUE THREAD

**Issue by chupkes** [netscaler/ansible-collection-netscaleradc#497]
### Summary

When attempting to update the Netscaler using netscaler.adc.install, the module returns "value of state must be one of: , got: present".

### Issue Type

Bug Report

### Component Name

install

### Python Version

```console (paste below)
$ python --version # or python3 --version
Python 3.12.3
```

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.16.3]
  config file = None
  configured module search path = ['/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```

### Ansible Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### netscaler.adc Collection Version

```console (paste below)
$ ansible-galaxy collection list netscaler.adc
netscaler.adc:2.8.0
```

### Target NetScaler Version

```console (paste below)
> show ns version
NetScaler NS13.1: Build 56.18.nc, Date: Nov  7 2024, 19:22:48   (64-bit)
```

### Equivalent NetScaler CLI Command

```console (paste below)
install <url> -A -L -y
```

### Steps to Reproduce

```yaml (paste below)
     
    - name: Install new firmware version
      delegate_to: localhost
      netscaler.adc.install: 
        nsip: "{{ nsip }}"
        url: "{{ firmware_url }}" 
        a: true #enable ADM Service Connect
        l: true #enable Callhome
        y: true #enable automatic reboot after update
        state: present
```
It's been a few months since I last tried, but I believe leaving out 'state' just defaults it to null, resulting in nearly the same error.

### Expected Results

New software should be installed.

### Actual Results

```console (paste below)
{
  "msg": "value of state must be one of: , got: present",
  "invocation": {
    "module_args": {
      "nitro_user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "nitro_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "nitro_protocol": "https",
      "validate_certs": false,
      "save_config": true,
      "nsip": "removed",
      "url": "https://removed/build-13.1-57.26_nc_64.tgz",
      "a": true,
      "l": true,
      "y": true,
      "state": "present",
      "api_path": "nitro/v1/config",
      "netscaler_console_as_proxy_server": false,
      "nitro_auth_token": null,
      "managed_netscaler_instance_name": null,
      "managed_netscaler_instance_ip": null,
      "managed_netscaler_instance_id": null,
      "managed_netscaler_instance_username": null,
      "managed_netscaler_instance_password": null,
      "async": null,
      "enhancedupgrade": null,
      "resizeswapvar": null
    }
  },
  "_ansible_no_log": false,
  "changed": false,
  "_ansible_delegated_vars": {
    "ansible_host": "localhost",
    "ansible_port": null,
    "ansible_user": "root",
    "ansible_connection": "local"
  }
}
```
